/**
 * @file comp_generation.cpp
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Implementation of functions for generating test data for sorting algorithms.
 * @date 10.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#include "comp_generation.h"

void generateRandom(vector<int>& toSort) {
   for (int& i : toSort)
      i = rand() % toSort.size() + 1;
}

void generateOrdered(vector<int>& toSort) {
   for (int i = 0; i < toSort.size(); i++)
      toSort[i] = i;
}

void generateReversed(vector<int>& toSort) {
   for (int i = 0; i < toSort.size(); i++)
      toSort[i] = toSort.size() - i;
}