/**
 * @file comp_sorts.h
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Sorting algorithms for comparison
 * @date 11.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#pragma once
#include <vector>

using namespace std;

/**
 * 2TSort algorithm for comparation.
 *
 * This is only shortened version.
 * For more info check original [2TSort.cpp] in root.
 */
void _2TSort(vector<int>& toSort);

/** Quick sort algorithm for comparation. */
void quickSort(vector<int>& toSort);

/** Bubble sort algorithm for comparation. */
void bubbleSort(vector<int>& toSort);

/** Insertion sort algorithm for comparation. */
void insertionSort(vector<int>& toSort);

/** Selection sort algorithm for comparation. */
void selectionSort(vector<int>& toSort);