/**
 * @file comp_setup_cleanup.h
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Setup and cleanup util for sorting tests
 * @date 10.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#pragma once
#include <cstdlib>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

using namespace std;

/**
 * @brief Clean [toSort] and set new size from [argv]
 * @param argc Program arguments count
 * @param argv Program arguments
 * @param toSort Vector to clear and set
 */
void setSortSize(int argc, char* argv[], vector<int>& toSort);