/**
 * @file comp_compare.cpp
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Comparation of 2TSort and other sorting algorithms
 * @date 11.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#include "comp_compare.h"

int main(int argc, char* argv[]) {
   srand(time(nullptr));  // to have random numbers

   // sort algorithms that will be compared
   vector<SortAlgoData> sortsData = {
       {"2TSort", _2TSort, AlgoTimes()},
       {"QuickSort", quickSort, AlgoTimes()},
       {"BubbleSort", bubbleSort, AlgoTimes()},
       {"InsertionSort", insertionSort, AlgoTimes()},
       {"SelectionSort", selectionSort, AlgoTimes()},
   };

   // types of order of generated numbers
   SortType cases[] = {
       {"Random", generateRandom, &AlgoTimes::random_numbers},
       {"Ordered", generateOrdered, &AlgoTimes::ordered},
       {"Reversed", generateReversed, &AlgoTimes::reversed}};

   printWholeIndicator("⌛");

   for (SortType& c : cases) {
      cout << c.title << ":" << endl;
      for (SortAlgoData& sortAlg : sortsData) {
         cout << "  " << sortAlg.name;

         vector<int> toSort;
         setSortSize(argc, argv, toSort);
         c.generator(toSort);

         auto start = chrono::high_resolution_clock::now();
         sortAlg.exec(toSort);
         auto end = chrono::high_resolution_clock::now();

         sortAlg.times.*(c.duration) = end - start;

         cout << right << setfill('.') << setw(19 - sortAlg.name.length()) << "✅" << endl;
      }
   }

   printWholeIndicator("✅");
   printResults(sortsData);

   return 0;
}

void printResults(vector<SortAlgoData> sortsData) {
   ofstream fout("comp_out.txt", ofstream::out | ofstream::trunc);
   ostream* out;

   if (!fout.is_open())
      out = &cout;
   else
      out = &fout;

   (*out)
       << endl
       << "+------------------------------------------------+"
       << endl
       << "| "
       << left << setw(13) << "Algorithm"
       << " | " << right << setw(8) << "Random"
       << " | " << right << setw(8) << "Ordered"
       << " | " << right << setw(8) << "Reversed"
       << " |"
       << " (ms)"
       << endl
       << "+------------------------------------------------+"
       << endl;

   for (const auto& sortAlg : sortsData) {
      (*out)
          << "| "
          << left << setw(13) << sortAlg.name
          << " | " << right << setw(8) << sortAlg.times.random_numbers.count()
          << " | " << right << setw(8) << sortAlg.times.ordered.count()
          << " | " << right << setw(8) << sortAlg.times.reversed.count()
          << " |"
          << endl;
   }

   (*out)
       << "+------------------------------------------------+"
       << endl
       << endl;
}

void printWholeIndicator(string emoji) {
   cout << endl
        << "   ";

   for (int c = 0; c < 7; c++)
      cout << emoji;

   cout << endl
        << endl;
}