/**
 * @file comp_generation.h
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Functions for generating test data for sorting algorithms
 * @date 11.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#pragma once
#include <cstdlib>
#include <vector>
using namespace std;

/**
 * @brief Generates random numbers (1 to toSort.size)
 * @param toSort vector to generate into
 */
void generateRandom(vector<int>& toSort);

/**
 * @brief Generates ascending numbers (1 to toSort.size)
 * @param toSort vector to generate into
 */
void generateOrdered(vector<int>& toSort);

/**
 * @brief Generates descending numbers (toSort.size to 1)
 * @param toSort vector to generate into
 */
void generateReversed(vector<int>& toSort);