/**
 * @file comp_setup_cleanup.cpp
 * @author Generated by Github Copilot
 * @author TeslaRam https://github.com/TeslaRam
 * @brief Implementation of setup and cleanup util for sorting tests
 * @date 11.7.25
 * @see https://github.com/TeslaRam/2TSort
 */

#include "comp_setup_cleanup.h"

void setSortSize(int argc, char* argv[], vector<int>& toSort) {
   try {
      toSort.clear();

      if (argc != 2) throw invalid_argument("argc != 2");

      int size = stoi(argv[1]);

      if (size < 1) throw invalid_argument("not int || is not > 1");

      toSort.resize(size);
   } catch (const exception& e) {
      cout << "Error: " << e.what() << endl;
      exit(1);
   }
}
